# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build VN project
      uses: ProjectAliceDev/renpy-build-action@master
      with:
        sdk-version: '7.3.5'
        project-dir: '.'
      env:
        SDL_AUDIODRIVER: dummy
        SDL_VIDEODRIVER: dummy
    - run: pwd
    - run: ls
  upload: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: pwd
      - run: ls
      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with: 
          path: friendsim-1.0-dists
